# -*- coding: utf-8 -*-
"""Problem2(Q-Learning, SARSA)_3조(최윤석,김영민)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxnPo0PwdluKK4uNGe9_-fCMXHrGp5Ek
"""

!pip install gymnasium==1.0.0 minigrid

# Commented out IPython magic to ensure Python compatibility.
# Drive Mount
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Colab Notebooks/

# ===================== 라이브러리 로드 =====================
import numpy as np
import matplotlib.pyplot as plt
import random
from tqdm import tqdm
import io
import imageio
from base64 import b64encode
from IPython.display import HTML

# Gym & MiniGrid
import gymnasium as gym
from gymnasium.spaces import Text
from minigrid.minigrid_env import MiniGridEnv
from minigrid.core.grid import Grid
from minigrid.core.world_object import Wall, Goal

# ===================== 사용자 정의 환경 =====================
class SimpleEnv(MiniGridEnv):
    def __init__(self, size=6, agent_start_pos=(1, 1), agent_start_dir=0, **kwargs):
        self.agent_start_pos = agent_start_pos
        self.agent_start_dir = agent_start_dir

        mission_space = Text(max_length=64)
        super().__init__(
            grid_size=size,
            max_steps=4 * size * size,
            agent_view_size=3,
            mission_space=mission_space,
            **kwargs
        )

        self.action_space = gym.spaces.Discrete(3)  # Left, Right, Forward

    @staticmethod
    def _gen_mission():
        return "grand mission"

    def _gen_grid(self, width, height):
        self.grid = Grid(width, height)
        self.grid.wall_rect(0, 0, width, height)

        wall_positions = [
            (1, 3), (1, 4),
            (2, 1), (2, 3),
            (3, 3),
            (4, 1), (4, 5),
            (5, 5),
        ]
        for pos in wall_positions:
            self.put_obj(Wall(), *pos)

        self.put_obj(Goal(), width - 2, height - 2)  #  유효한 내부 위치

        self.agent_pos = self.agent_start_pos
        self.agent_dir = self.agent_start_dir
        self.mission = "Reach the green goal square"

# ===================== Epsilon-Greedy =====================
def eps_greedy(Q_values, state, epsilon=1.0):
    if random.random() < epsilon:
        return random.randint(0, 2)  # 3개 행동 중 무작위
    else:
        return int(np.argmax(Q_values[state]))

# ===================== Q-Learning =====================
def run(env, Q_values, n_episodes, epsilon, epsilon_decay, gamma, lr):
    total_rewards = []

    for ep in tqdm(range(n_episodes)):
        obs, info = env.reset()
        state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
        done = False
        ep_reward = 0

        while not done:
            action = eps_greedy(Q_values, state, epsilon)
            next_obs, reward, terminated, truncated, info = env.step(action)
            next_state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
            done = terminated or truncated

            best_next_q = np.max(Q_values[next_state])
            td_target = reward + gamma * best_next_q
            td_error = td_target - Q_values[state][action]
            Q_values[state][action] += lr * td_error

            state = next_state
            ep_reward += reward

        epsilon *= epsilon_decay
        total_rewards.append(ep_reward)

    return Q_values, total_rewards

# ===================== 학습 실행 =====================
env = SimpleEnv(render_mode="rgb_array")
Q_values = np.zeros((env.width, env.height, 4, env.action_space.n))  # (x, y, dir, action)

Q_values, rewards = run(
    env,
    Q_values,
    n_episodes=5000,
    epsilon=1.0,
    epsilon_decay=0.999,  #  더 천천히 감소
    gamma=0.99,
    lr=0.1
)

# ===================== 보상 시각화 =====================
plt.plot(rewards)
plt.xlabel("Episodes")
plt.ylabel("Total Reward")
plt.title("Q-Learning Reward Plot")
plt.grid(True)
plt.show()

# ===================== 학습된 정책 테스트 =====================
frames = []
obs, info = env.reset()
state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
done = False
trajectory = [state]
frames.append(env.render())

while not done:
    action = np.argmax(Q_values[state])
    obs, reward, terminated, truncated, info = env.step(action)
    state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
    trajectory.append(state)
    frames.append(env.render())
    done = terminated or truncated

# ===================== Trajectory 출력 =====================
print(" State trajectory (x, y, direction):")
for s in trajectory:
    print(s)

# ===================== 동영상 표시 함수 =====================
def display_video(frames, fps=1):
    video = io.BytesIO()
    imageio.mimsave(video, frames, format="mp4", fps=fps)
    video.seek(0)
    data_url = b64encode(video.read()).decode()
    return HTML(f"""
    <video width="640" height="480" controls>
        <source src="data:video/mp4;base64,{data_url}" type="video/mp4">
    </video>
    """)

# ▶️ 시각화
display_video(frames)

!pip install gymnasium minigrid

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Colab Notebooks/

# 필수 모듈 재임포트
import numpy as np
import random
import matplotlib.pyplot as plt
from tqdm import tqdm
import gymnasium as gym
from gymnasium.spaces import Text
from minigrid.minigrid_env import MiniGridEnv
from minigrid.core.grid import Grid
from minigrid.core.world_object import Wall, Goal

# 사용자 정의 Minigrid 환경
class SimpleEnv(MiniGridEnv):
    def __init__(self, size=6, agent_start_pos=(1, 1), agent_start_dir=0, **kwargs):
        self.agent_start_pos = agent_start_pos
        self.agent_start_dir = agent_start_dir
        mission_space = Text(max_length=64)
        super().__init__(
            grid_size=size,
            max_steps=4 * size * size,
            agent_view_size=3,
            mission_space=mission_space,
            **kwargs
        )
        self.action_space = gym.spaces.Discrete(3)  # left, right, forward

    @staticmethod
    def _gen_mission():
        return "Reach the goal"

    def _gen_grid(self, width, height):
        self.grid = Grid(width, height)
        self.grid.wall_rect(0, 0, width, height)

        wall_positions = [
            (1, 3), (1, 4),
            (2, 3),
            (3, 3),
            (4, 1), (4, 5),
            (5, 5),
        ]
        for pos in wall_positions:
            self.put_obj(Wall(), *pos)

        self.put_obj(Goal(), width - 2, height - 2)
        self.agent_pos = self.agent_start_pos
        self.agent_dir = self.agent_start_dir
        self.mission = "Reach the green goal square"

# Epsilon-greedy 정책
def eps_greedy(Q_values, state, epsilon=1.0):
    if random.random() < epsilon:
        action = random.randint(0, 2)
    else:
        action = int(np.argmax(Q_values[state[0], state[1], state[2]]))
    return action

# SARSA 학습 함수
def run_sarsa(env, Q_values, n_episodes, epsilon, epsilon_decay, gamma, lr):
    total_rewards = []
    for _ in tqdm(range(n_episodes)):
        obs, info = env.reset()
        state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
        action = eps_greedy(Q_values, state, epsilon)
        done = False
        ep_reward = 0

        while not done:
            next_obs, reward, terminated, truncated, info = env.step(action)
            next_state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
            done = terminated or truncated
            next_action = eps_greedy(Q_values, next_state, epsilon)

            # SARSA 업데이트
            td_target = reward + gamma * Q_values[next_state][next_action]
            td_error = td_target - Q_values[state][action]
            Q_values[state][action] += lr * td_error

            state = next_state
            action = next_action
            ep_reward += reward

        epsilon *= epsilon_decay
        total_rewards.append(ep_reward)
    return Q_values, total_rewards

# 환경 및 학습 실행
env = SimpleEnv(render_mode="rgb_array", agent_start_pos=(1, 1))
Q_values = np.zeros((env.width, env.height, 4, 3))

Q_values, rewards = run_sarsa(
    env,
    Q_values,
    n_episodes=5000,
    epsilon=1.0,
    epsilon_decay=0.995,
    gamma=0.99,
    lr=0.1
)

# 리워드 그래프 시각화
plt.plot(rewards)
plt.xlabel("Episodes")
plt.ylabel("Total Reward")
plt.title("SARSA Reward Plot")
plt.grid(True)
plt.show()

# 에이전트의 trajectory 수집 및 시각화
trajectory = []
frames = []
obs, info = env.reset()
state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
trajectory.append(state)
frames.append(env.render())
done = False

while not done:
    action = np.argmax(Q_values[state])
    obs, reward, terminated, truncated, info = env.step(action)
    state = (env.agent_pos[0], env.agent_pos[1], env.agent_dir)
    trajectory.append(state)
    frames.append(env.render())
    done = terminated or truncated

# ✔️ 출력 정리
print("✅ State trajectory (x, y, direction):")
for s in trajectory:
    x, y, d = map(int, s)
    print(f"({x}, {y}, {d})")

# 비디오 시각화 함수
import io
import imageio
from base64 import b64encode
from IPython.display import HTML

def display_video(frames, fps=1):
    video = io.BytesIO()
    imageio.mimsave(video, frames, format="mp4", fps=fps)
    video.seek(0)
    data_url = b64encode(video.read()).decode()
    return HTML(f"""
    <video width="640" height="480" controls>
        <source src="data:video/mp4;base64,{data_url}" type="video/mp4">
    </video>
    """)

# 비디오 재생
display_video(frames)