# -*- coding: utf-8 -*-
"""Problem3(DQN)_3조(최윤석, 김영민)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qBnsjQLJEOi2YbR8fb92J1trAv-HHb8
"""

!pip install gymnasium==1.0.0 minigrid

!pip install gym-minigrid

# Commented out IPython magic to ensure Python compatibility.
# ------------------ Drive Mount ------------------
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Colab Notebooks/

# ------------------ 기본 패키지 ------------------
import numpy as np, random, torch, torch.nn as nn, torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt
from collections import deque
from tqdm import tqdm
import torchvision.transforms as transforms
import gymnasium as gym
from gymnasium.spaces import Text
from minigrid.minigrid_env import MiniGridEnv
from minigrid.core.grid import Grid
from minigrid.core.world_object import Wall, Goal
from minigrid.wrappers import RGBImgPartialObsWrapper
import time, os, imageio
from IPython.display import HTML, display
from datetime import datetime
import io
from base64 import b64encode

# ------------------ 1. 환경 정의 ------------------
class SimpleEnv(MiniGridEnv):
    def __init__(self, size=6, agent_start_pos=(1, 1), agent_start_dir=0, mission_space=None, **kwargs):
        self.agent_start_pos = agent_start_pos
        self.agent_start_dir = agent_start_dir
        self.goal_pos = (size - 2, size - 2)
        if mission_space is None:
            mission_space = Text(max_length=64)
        super().__init__(grid_size=size, max_steps=4*size*size,
                         agent_view_size=5, mission_space=mission_space, **kwargs)
        self.action_space = gym.spaces.Discrete(3)

    def _gen_grid(self, width, height):
        self.grid = Grid(width, height)
        self.grid.wall_rect(0, 0, width, height)
        for pos in [(1, 3), (1, 4), (2, 3), (3, 3), (4, 1), (4, 5), (5, 5)]:
            self.put_obj(Wall(), *pos)
        self.put_obj(Goal(), *self.goal_pos)
        self.agent_pos = self.agent_start_pos
        self.agent_dir = self.agent_start_dir

    def step(self, action):
        obs, reward, terminated, truncated, info = super().step(action)
        if not terminated:
            reward = -0.01
        if self.agent_pos == self.goal_pos:
            reward = 1.0
        return obs, reward, terminated, truncated, info

# ------------------ 2. Replay Buffer ------------------
class ReplayBuffer:
    def __init__(self, capacity):
        self.buffer = deque(maxlen=capacity)
    def push(self, s, a, r, s_, d):
        self.buffer.append((s, a, r, s_, d))
    def sample(self, batch_size):
        s, a, r, s_, d = zip(*random.sample(self.buffer, batch_size))
        return s, a, r, s_, d
    def __len__(self):
        return len(self.buffer)

# ------------------ 3. DQN Model ------------------
class DQN(nn.Module):
    def __init__(self, input_shape, num_actions):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(input_shape[0], 16, 5, stride=1), nn.ReLU(),
            nn.Conv2d(16, 32, 3, stride=1), nn.ReLU(),
            nn.Conv2d(32, 32, 3, stride=1), nn.ReLU()
        )
        with torch.no_grad():
            dummy = torch.zeros(1, *input_shape)
            conv_out = self.conv(dummy)
            self.flat_dim = int(np.prod(conv_out.size()))
        self.fc = nn.Sequential(
            nn.Linear(self.flat_dim, 256), nn.ReLU(),
            nn.Linear(256, num_actions)
        )
    def forward(self, x):
        x = self.conv(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

# ------------------ 4. 이미지 전처리 ------------------
def preprocess(obs):
    image = torch.tensor(obs['image'], dtype=torch.float32).permute(2, 0, 1) / 255.0
    image = transforms.Grayscale()(image)
    return image.unsqueeze(0)

# ------------------ 5. ε-Greedy 정책 ------------------
def select_action(model, state, epsilon, num_actions):
    if random.random() < epsilon:
        return random.randint(0, num_actions - 1)
    with torch.no_grad():
        q_values = model(state)
        return q_values.argmax().item()

# ------------------ 6. DQN 학습 루프 ------------------
def train_dqn(env, model, target_model, buffer, optimizer,
              episodes, batch_size, gamma, epsilon, epsilon_decay, update_freq=20):
    rewards = []
    for ep in tqdm(range(episodes)):
        obs, _ = env.reset()
        state = preprocess(obs).to(device)
        done, total_reward = False, 0

        while not done:
            action = select_action(model, state, epsilon, env.action_space.n)
            obs_, reward, terminated, truncated, _ = env.step(action)
            next_state = preprocess(obs_).to(device)
            done = terminated or truncated
            buffer.push(state, action, reward, next_state, done)
            state = next_state
            total_reward += reward

            if len(buffer) >= batch_size:
                b = buffer.sample(batch_size)
                s = torch.cat(b[0]).to(device)
                a = torch.tensor(b[1]).unsqueeze(1).to(device)
                r = torch.tensor(b[2], dtype=torch.float32).unsqueeze(1).to(device)
                s_ = torch.cat(b[3]).to(device)
                d = torch.tensor(b[4], dtype=torch.float32).unsqueeze(1).to(device)

                q = model(s).gather(1, a)
                with torch.no_grad():
                    max_q = target_model(s_).max(1)[0].unsqueeze(1)
                    target = r + gamma * max_q * (1 - d)

                loss = F.mse_loss(q, target)
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

        epsilon = max(epsilon * epsilon_decay, 0.01)
        rewards.append(total_reward)

        if ep % update_freq == 0:
            target_model.load_state_dict(model.state_dict())

    return rewards

# ------------------ 7. 학습 ------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
env = RGBImgPartialObsWrapper(SimpleEnv(render_mode="rgb_array"))
input_shape = preprocess(env.reset()[0]).shape[1:]
num_actions = env.action_space.n

model = DQN(input_shape, num_actions).to(device)
target_model = DQN(input_shape, num_actions).to(device)
target_model.load_state_dict(model.state_dict())

optimizer = optim.Adam(model.parameters(), lr=1e-4)
buffer = ReplayBuffer(10000)

rewards = train_dqn(env, model, target_model, buffer, optimizer,
                    episodes=1000, batch_size=32, gamma=0.99,
                    epsilon=1.0, epsilon_decay=0.999)

model.eval()
torch.save(model.state_dict(), "/content/drive/MyDrive/DQN_model.pth")

# ------------------ 8. 보상 시각화 ------------------
plt.plot(rewards)
plt.xlabel("Episodes")
plt.ylabel("Total Reward")
plt.title("DQN Reward Plot")
plt.grid()
plt.show()

# ------------------ 9. 테스트 및 시각화 ------------------
def display_video(frames, fps=3):
    video = io.BytesIO()
    imageio.mimsave(video, frames, format="mp4", fps=fps)
    video.seek(0)
    data_url = b64encode(video.read()).decode()
    return HTML(f"""
    <video width="640" height="480" controls>
        <source src="data:video/mp4;base64,{data_url}" type="video/mp4">
    </video>
    """)

frames = []
obs, info = env.reset()
done = False
trajectory = []
frames.append(env.render())

while not done:
    with torch.no_grad():
        state_tensor = preprocess(obs).to(device)
        q_values = model(state_tensor)
        action = q_values.argmax().item()

    obs, reward, terminated, truncated, info = env.step(action)
    trajectory.append((env.unwrapped.agent_pos[0], env.unwrapped.agent_pos[1], env.unwrapped.agent_dir))
    frames.append(env.render())
    done = terminated or truncated

print("\n✅ State trajectory (x, y, direction):")
for s in trajectory:
    print(s)

display(display_video(frames, fps=3))

