# -*- coding: utf-8 -*-
"""Problem1(Maze Environment)_3조_(최윤석, 김영민)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kMlqtLFk4mJq-U26bHyQpVc3YF4ks4VU
"""

!pip install numpy
!pip install minigrid
!pip install gymnasium==1.0.0
!pip install matplotlib

import gymnasium as gym
from gymnasium.spaces import Text
from minigrid.minigrid_env import MiniGridEnv
from minigrid.core.grid import Grid
from minigrid.core.world_object import Wall, Goal

# 사용자 정의 6x6 미로 환경
class CustomMazeEnv(MiniGridEnv):
    def __init__(self, size=6, render_mode=None):
        self.size = size
        mission_space = Text(max_length=64)

        super().__init__(
            grid_size=size,
            max_steps=4 * size * size,
            agent_view_size=3,
            mission_space=mission_space,
            render_mode=render_mode
        )

        self.action_space = gym.spaces.Discrete(3)  # 좌, 우, 전진(Three Actions)

    def _gen_grid(self, width, height):
        self.grid = Grid(width, height)
        self.grid.wall_rect(0, 0, width, height)

        # 슬라이드 기반 벽 위치 (에이전트 위치와 겹치지 않도록 (1,1)은 제외)
        wall_positions = [
            (1, 3), (1, 4),
            (2, 1), (2, 3),
            (3, 3),
            (4, 1), (4, 5),
            (5, 5),
        ]
        for pos in wall_positions:
            self.put_obj(Wall(), *pos)

        # 종료 지점 (6,6) → 인덱스 기준 (5,5)
        self.put_obj(Goal(), 5, 5)

        # 시작 위치 (1,1) → 인덱스 기준 (1,1) ← (1,1)이 이제 비어 있음
        self.agent_pos = (1, 1)
        self.agent_dir = 0
        self.mission = "Reach the green goal square"

import matplotlib.pyplot as plt

# 환경 생성 및 리셋
env = CustomMazeEnv(render_mode="rgb_array")
obs, _ = env.reset()

# 이미지 렌더링
image = env.render()

# 출력
plt.imshow(image)
plt.axis("off")
plt.title("6x6 Maze Matching Slide Example")
plt.show()

